# Generated by Django 6.0.5 on 2026-05-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.URLField(blank=True, null=True),
        ),
    ]
